//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.UI.ASPNetMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TICRM.UI.ASPNetMVC.Resources.SuccessMessage", typeof(SuccessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account submitted successfully..
        /// </summary>
        internal static string AccountSubmit {
            get {
                return ResourceManager.GetString("AccountSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity submitted successfully..
        /// </summary>
        internal static string ActivitySubmit {
            get {
                return ResourceManager.GetString("ActivitySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address submitted successfully..
        /// </summary>
        internal static string AddressSubmit {
            get {
                return ResourceManager.GetString("AddressSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case submitted successfully..
        /// </summary>
        internal static string CaseSubmit {
            get {
                return ResourceManager.GetString("CaseSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact submitted successfully..
        /// </summary>
        internal static string ContactSubmit {
            get {
                return ResourceManager.GetString("ContactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Asset submitted successfully..
        /// </summary>
        internal static string CustomerAssetSubmit {
            get {
                return ResourceManager.GetString("CustomerAssetSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data submitted successfully..
        /// </summary>
        internal static string DeviceSensorSubmit {
            get {
                return ResourceManager.GetString("DeviceSensorSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device submitted successfully..
        /// </summary>
        internal static string DeviceSuccess {
            get {
                return ResourceManager.GetString("DeviceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configured successfully..
        /// </summary>
        internal static string EmaiLSubmit {
            get {
                return ResourceManager.GetString("EmaiLSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware submitted successfully..
        /// </summary>
        internal static string FirmwareSubmit {
            get {
                return ResourceManager.GetString("FirmwareSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead submitted successfully..
        /// </summary>
        internal static string LeadSubmit {
            get {
                return ResourceManager.GetString("LeadSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location submitted successfully..
        /// </summary>
        internal static string LocationSubmit {
            get {
                return ResourceManager.GetString("LocationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity submitted successfully..
        /// </summary>
        internal static string OpportunitySubmit {
            get {
                return ResourceManager.GetString("OpportunitySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        internal static string PasswordChangedSubmit {
            get {
                return ResourceManager.GetString("PasswordChangedSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Link submitted successfully..
        /// </summary>
        internal static string PaymentLinkSubmit {
            get {
                return ResourceManager.GetString("PaymentLinkSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources submitted successfully..
        /// </summary>
        internal static string ResourceSubmit {
            get {
                return ResourceManager.GetString("ResourceSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Call submitted successfully..
        /// </summary>
        internal static string ServiceCallSubmit {
            get {
                return ResourceManager.GetString("ServiceCallSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow mapping submited successfully..
        /// </summary>
        internal static string WorkFlowMappingSubmit {
            get {
                return ResourceManager.GetString("WorkFlowMappingSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work flow report submitted successfully..
        /// </summary>
        internal static string WorkFlowReportSubmit {
            get {
                return ResourceManager.GetString("WorkFlowReportSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkFlow submitted successfully..
        /// </summary>
        internal static string WorkFlowSubmit {
            get {
                return ResourceManager.GetString("WorkFlowSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order submitted successfully..
        /// </summary>
        internal static string WorkOrderSubmit {
            get {
                return ResourceManager.GetString("WorkOrderSubmit", resourceCulture);
            }
        }
    }
}
