//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.UI.ASPNetMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TICRM.UI.ASPNetMVC.Resources.UpdateMessage", typeof(UpdateMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated Successfully..
        /// </summary>
        internal static string AccountUpdate {
            get {
                return ResourceManager.GetString("AccountUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity updated Successfully..
        /// </summary>
        internal static string ActivityUpdate {
            get {
                return ResourceManager.GetString("ActivityUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address updated successfully..
        /// </summary>
        internal static string AddressUpdate {
            get {
                return ResourceManager.GetString("AddressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case updated Successfully..
        /// </summary>
        internal static string CaseUpdate {
            get {
                return ResourceManager.GetString("CaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact updated Successfully..
        /// </summary>
        internal static string ContactUpdate {
            get {
                return ResourceManager.GetString("ContactUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Asset updated successfully..
        /// </summary>
        internal static string CustomerAssetUpdate {
            get {
                return ResourceManager.GetString("CustomerAssetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        internal static string DeviceSensorUpdate {
            get {
                return ResourceManager.GetString("DeviceSensorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device updated successfully..
        /// </summary>
        internal static string DeviceUpdate {
            get {
                return ResourceManager.GetString("DeviceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email configuration updated Successfully..
        /// </summary>
        internal static string EmailUpdate {
            get {
                return ResourceManager.GetString("EmailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead updated successfully..
        /// </summary>
        internal static string LeadUpdate {
            get {
                return ResourceManager.GetString("LeadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location updated Successfully..
        /// </summary>
        internal static string LocationUpdate {
            get {
                return ResourceManager.GetString("LocationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity updated successfully..
        /// </summary>
        internal static string OpportunityUpdate {
            get {
                return ResourceManager.GetString("OpportunityUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Link updated Successfully.
        /// </summary>
        internal static string PaymentLinkUpdate {
            get {
                return ResourceManager.GetString("PaymentLinkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated..
        /// </summary>
        internal static string ProfleUpdate {
            get {
                return ResourceManager.GetString("ProfleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource updated successfully..
        /// </summary>
        internal static string ResourceUpdate {
            get {
                return ResourceManager.GetString("ResourceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Call updated successfully..
        /// </summary>
        internal static string ServiceCallUpdate {
            get {
                return ResourceManager.GetString("ServiceCallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow mapping updated successfully..
        /// </summary>
        internal static string WorkFlowMappingUpdate {
            get {
                return ResourceManager.GetString("WorkFlowMappingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work flow report updated successfully..
        /// </summary>
        internal static string WorkFlowReportUpdate {
            get {
                return ResourceManager.GetString("WorkFlowReportUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkFlow updated Successfully..
        /// </summary>
        internal static string WorkFlowUpdate {
            get {
                return ResourceManager.GetString("WorkFlowUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order updated successfully..
        /// </summary>
        internal static string WorkOrderUpdate {
            get {
                return ResourceManager.GetString("WorkOrderUpdate", resourceCulture);
            }
        }
    }
}
