//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption
    {
        public System.Guid ConsumptionID { get; set; }
        public Nullable<System.Guid> DeviceId { get; set; }
        public string Current { get; set; }
        public string Voltage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Device Device { get; set; }
    }
}
