//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerAsset()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public System.Guid CustomerAssetId { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> CustomerAssetTypeId { get; set; }
        public string Manufacture { get; set; }
        public string Model { get; set; }
        public Nullable<int> YearOfManufacture { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> DepriciatedValue { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.Guid> AssignedUser { get; set; }
        public Nullable<System.Guid> AssignedTeam { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> Company { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual CustomerAssetType CustomerAssetType { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
