//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadAccount
    {
        public System.Guid LeadAccountId { get; set; }
        public System.Guid LeadId { get; set; }
        public System.Guid AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
