//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowMapping
    {
        public System.Guid WorkFlowMappingId { get; set; }
        public Nullable<System.Guid> WorkFlowId { get; set; }
        public string SourceType { get; set; }
        public string SourceColumn { get; set; }
        public string SourceValue { get; set; }
        public string SourceData { get; set; }
        public string Action { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
