//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Contacts = new HashSet<Contact>();
            this.LeadAccounts = new HashSet<LeadAccount>();
        }
    
        public System.Guid AccountId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ShippingAddress { get; set; }
        public Nullable<System.Guid> BillingAddress { get; set; }
        public Nullable<System.Guid> AccountTypeId { get; set; }
        public string PhoneOffice { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public Nullable<System.Guid> AccountSizeId { get; set; }
        public Nullable<System.Guid> IndustryId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.Guid> AssignedUser { get; set; }
        public Nullable<System.Guid> AssignedTeam { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AccountSize AccountSize { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<LeadAccount> LeadAccounts { get; set; }
    }
}
