//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Opportunities = new HashSet<Opportunity>();
            this.ProductPriceLists = new HashSet<ProductPriceList>();
        }
    
        public System.Guid CurrencyId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Sign { get; set; }
    
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<ProductPriceList> ProductPriceLists { get; set; }
    }
}
