//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmware
    {
        public int Id { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string server { get; set; }
        public string File { get; set; }
        public string Location { get; set; }
        public string Device { get; set; }
    }
}
