//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingType
    {
        public ReadingType()
        {
            this.Readings = new HashSet<Reading>();
            this.ReadingUnits = new HashSet<ReadingUnit>();
        }
    
        public System.Guid ReadingTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Reading> Readings { get; set; }
        public virtual ICollection<ReadingUnit> ReadingUnits { get; set; }
    }
}
