//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urgency
    {
        public Urgency()
        {
            this.Alerts = new HashSet<Alert>();
            this.ServiceCalls = new HashSet<ServiceCall>();
        }
    
        public System.Guid UrgencyId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<ServiceCall> ServiceCalls { get; set; }
    }
}
