//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.Activities = new HashSet<Activity>();
            this.Alerts = new HashSet<Alert>();
            this.Categories = new HashSet<Category>();
            this.Contacts = new HashSet<Contact>();
            this.CustomerAssets = new HashSet<CustomerAsset>();
            this.Devices = new HashSet<Device>();
            this.Emails = new HashSet<Email>();
            this.Leads = new HashSet<Lead>();
            this.Locations = new HashSet<Location>();
            this.Meetings = new HashSet<Meeting>();
            this.Opportunities = new HashSet<Opportunity>();
            this.PhoneCalls = new HashSet<PhoneCall>();
            this.ProductCatelogs = new HashSet<ProductCatelog>();
            this.Readings = new HashSet<Reading>();
            this.Resources = new HashSet<Resource>();
            this.ResourceAvailabilities = new HashSet<ResourceAvailability>();
            this.ResourceSkills = new HashSet<ResourceSkill>();
            this.ServiceCalls = new HashSet<ServiceCall>();
            this.Tasks = new HashSet<Task>();
            this.TeamUsers = new HashSet<TeamUser>();
            this.WorkFlows = new HashSet<WorkFlow>();
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<CustomerAsset> CustomerAssets { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<PhoneCall> PhoneCalls { get; set; }
        public virtual ICollection<ProductCatelog> ProductCatelogs { get; set; }
        public virtual ICollection<Reading> Readings { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<ResourceAvailability> ResourceAvailabilities { get; set; }
        public virtual ICollection<ResourceSkill> ResourceSkills { get; set; }
        public virtual ICollection<ServiceCall> ServiceCalls { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TeamUser> TeamUsers { get; set; }
        public virtual ICollection<WorkFlow> WorkFlows { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
