//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.MQTT.Listner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public System.Guid CaseId { get; set; }
        public string CaseTitle { get; set; }
        public System.Guid CaseTypeId { get; set; }
        public long ContactId { get; set; }
        public string Origin { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AssignedTeam { get; set; }
        public Nullable<System.Guid> AssignedUser { get; set; }
        public string RelatedTo { get; set; }
        public Nullable<System.Guid> CaseStatusId { get; set; }
        public Nullable<System.Guid> ResolutionType { get; set; }
        public string Resolution { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> BillableTime { get; set; }
        public string Remarks { get; set; }
        public System.Guid RelatedToId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Scheduling { get; set; }
        public string Reading { get; set; }
        public Nullable<System.Guid> SensorId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
    
        public virtual CaseResolution CaseResolution { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual CaseStatu CaseStatu { get; set; }
        public virtual CaseType CaseType { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
