//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.MQTT.Listner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public System.Guid CostsId { get; set; }
        public string Cost1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> UnitCostId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
    
        public virtual UnitCost UnitCost { get; set; }
        public virtual Account Account { get; set; }
    }
}
