//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.MQTT.Listner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeciveConfiguration
    {
        public System.Guid DeviceConfigurationId { get; set; }
        public Nullable<System.Guid> DeviceId { get; set; }
        public Nullable<bool> IsSleepModeEnabled { get; set; }
        public Nullable<int> SleepModeValueInSeconds { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
