//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICRM.MQTT.Listner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public System.Guid Id { get; set; }
        public string Devicemac { get; set; }
        public string Devicelocation { get; set; }
        public System.DateTime Datatime { get; set; }
    }
}
