// <auto-generated />
namespace TICRM.UI.ASPNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcompanyindustry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcompanyindustry));
        
        string IMigrationMetadata.Id
        {
            get { return "202305250618154_add-company-industry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
